### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by gugani** [f-koehler/KTailctl#12]
App menu and tray icons missing. Installed via Flatpak in kubuntu 23.04. 
![Screenshot_20230601_192838](https://github.com/f-koehler/KTailctl/assets/2253797/30fa0f4d-0fc7-4623-affe-9f4c0d2ebaa2)
![Screenshot_20230601_193239](https://github.com/f-koehler/KTailctl/assets/2253797/fe2042d4-15a4-43bb-a395-b86dd81446c6)

**Comment by f-koehler** [comment]
Interesting, it works on my machine™ maybe I still had the icons installed from the manual installation but they do not get put into the flatpak. Will investigate.

Does the tray icon have an icon on you system? Or is that missing as well?

**Comment by gugani** [comment]
Hi @f-koehler , the tray icon is missing. I have changed the Plasma theme to check if the problem is that the icon was black, but without success. Only a blank space where the tray icon should be.

**Comment by f-koehler** [comment]
Thanks for getting back to me. I edited my comment as I later read your comment more carefully, you already stated that it was missing as well.

Thanks for trying to switch the theme! This should not matter since the icons are installed under `/icons/hicolor/scalable/apps/` but still a good idea.

In the mean time I checked that the icons are present in the flatpak, which they are. So currently I am a bit puzzled what is going on here. At the moment I install a Kubuntu VM to have a clean environment to test in.

**Comment by f-koehler** [comment]
I was able to reproduce the issues. I already resolved the desktop entry not having an icon, turns out that in flatpaks the icon must be named after the application domain, in this case I had to rename `ktailctl.svg` to `org.fkoehler.KTailctl.svg`. Still do not now why this posed no problem on my machine. Version 0.3.2 should be published on flathub in the next few hours, resolving this issue. 

I will work on the tray icons next week.

**Comment by gugani** [comment]
Thanks @f-koehler. I will wait for the update and report back.

**Comment by gugani** [comment]
Hi @f-koehler, app updtad to 0.3.2. Menu launcher icon fixed, but the tray icon no, blank space where the tray icon should be. I have uninstall install the app, also deleting ~/.var/app/org.fkoehler.KTailctl folder, and reboot. One aditional note, I updated via KDE Discover, it notifies 0.3.1 -> 0.1.8. After updating the version number in the About section is correct, 0.3.2.

**Comment by SuperSweatyYeti** [comment]
> 

Confirming I am also missing system tray icon still

Running Fedora 38 KDE spin

**Comment by gugani** [comment]
Hi @f-koehler , update to 0.3.3 and the tray icon finally is ok. Thanks! Congrats, very nice app, I will be waiting for those new features.

**Comment by gugani** [comment]
Issue solved
