### ISSUE TITLE
Remove AppImage

### ISSUE THREAD

**Issue by f-koehler** [f-koehler/KTailctl#236]
Remove the AppImage build as I think flatpak and Snap (to be added in the future) are better technical solutions:

- AppImage relies on the EOL `fuse2` library
- AppImage seems to have no sandboxing at all
- Update management would have to be implemented manually
- Flatpak and snap are integrated into most of the common Linux desktop environments

**Comment by Samueru-sama** [comment]
Hi, I'm just a passerby and not a user of this project, but I thought I would respond to the points as they are simply not true: 


> AppImage relies on the EOL fuse2 library

Appimages made with **linuxdeploy** rely on fuse2. You can use the static runtime and that way you don't need fuse2, that also makes it able to run in musl distros provided of course that the binary inside the appimage can work in those. 

https://github.com/probonopd/go-appimage uses it by default. And a popular project that is made with it is the cemu emulator: https://github.com/cemu-project/Cemu/releases

Also as much as fuse2 is EOL, it is still the main fuse that's use in archlinux (dependency of [mtpfs](https://archlinux.org/packages/extra/x86_64/mtpfs/) and [ntfs-3g](https://archlinux.org/packages/extra/x86_64/ntfs-3g/)), which is a rolling release distro, they simply haven't bothered to make the switch.

>AppImage seems to have no sandboxing at all

Not by default: https://github.com/mgord9518/aisap

AppImage is just a format, and far better than the alternative before it which was zipped portable builds.

>Update management would have to be implemented manually

Maybe? both linuxdeploy and go-appimage let you setup zsync releases that let the appimage update with appimage-update-tool. But I personally don't use it since I handle the updating with AM (and iirc gearlever and zap do similar things)

>Flatpak and snap are integrated into most of the common Linux desktop environments

But not all. 

-----------------------------------------------------------------

Anyway, once again I'm not a user. Just responding to some of the points made, you are free to do anything, I know appimage can be a pain to maintain, specially when python gets involved lol.

**Comment by f-koehler** [comment]
@Samueru-sama Thanks for the clarifications as well as insights into the AppImage ecosystem! I might reconsider adding AppImage later when the project is a bit more mature. It is definitely that I hate AppImage or something like that, it is just too much for me to support atm. The AppImage was not really used (but I also did not promote it that much) and I think the flatpak should cover most use cases.

I was considering `appimage-update-tool` but it seemed too much of a hassle at the time. But I will definitely have another look in the future.
